name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build  # Wenn keine Build-Schritte erforderlich sind, kannst du diesen Schritt entfernen

    - name: Test Application
      run: npm test  # Wenn keine Tests vorhanden sind, kannst du diesen Schritt entfernen
